# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181215_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='group',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.AppGrp'),
        ),
    ]
