# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181219_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='appgrp',
            name='team',
            field=models.CharField(choices=[('FruitDay', 'FruitDay'), ('GW', 'GW'), ('OMS', 'OMS'), ('PMS', 'PMS'), ('SAP', 'SAP'), ('TMS', 'TMS')], default='FruitDay', max_length=32),
        ),
    ]
