# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appgrp_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='git_id',
            field=models.IntegerField(default=361),
        ),
    ]
