# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-29 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_app_git_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='packing_lock',
            field=models.BooleanField(default=False),
        ),
    ]
