# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-02 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='sort_id',
            new_name='short_id',
        ),
    ]
