# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-03 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190102_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
